"use client";

import React, { useCallback, useEffect, useState } from "react";

interface Summary {
  sessions: number;
  learners: number;
}

/**
 * Demo controls. Reset clears only the generated demo activity, so a real
 * learner's work is never affected, and reseeds so the dashboards are never left empty.
 */
export default function DemoAdminPage(): React.JSX.Element {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [confirming, setConfirming] = useState(false);

  const load = useCallback(async () => {
    try {
      const res = await fetch("/api/admin/demo/reset");
      if (!res.ok) throw new Error("The demo summary could not be loaded.");
      setSummary((await res.json()) as Summary);
    } catch (e) {
      setError(e instanceof Error ? e.message : "The demo summary could not be loaded.");
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    const timer = setTimeout(() => {
      if (!cancelled) void load();
    }, 0);
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [load]);

  const reset = useCallback(async () => {
    setBusy(true);
    setError(null);
    setMessage(null);
    try {
      const res = await fetch("/api/admin/demo/reset", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ keepUploadedContent: true, reseed: true }),
      });
      if (!res.ok) throw new Error("The reset did not complete. Try again.");
      const body = (await res.json()) as {
        removed: { sessions: number };
        reseeded: { sessions: number; learners: number } | null;
      };
      setMessage(
        `Removed ${body.removed.sessions} demo sessions and reseeded ${body.reseeded?.sessions ?? 0} for ${body.reseeded?.learners ?? 0} learners.`,
      );
      setConfirming(false);
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : "The reset did not complete. Try again.");
    } finally {
      setBusy(false);
    }
  }, [load]);

  return (
    <main className="mx-auto max-w-2xl px-4 py-8">
      <h1 className="text-ink text-xl font-bold tracking-tight">Demo data</h1>
      <p className="text-ink/70 mt-2 text-sm">
        The demo dataset is generated by running the real scoring and mastery functions over
        scripted answers. No model is called, so it is fast and costs nothing.
      </p>

      <section
        aria-label="Current demo data"
        className="border-mist mt-6 rounded-lg border bg-white p-4"
      >
        <dl className="grid grid-cols-2 gap-4 text-sm">
          <div>
            <dt className="text-ink/70 text-xs">Seeded learners</dt>
            <dd data-testid="demo-learners" className="text-ink text-lg font-semibold">
              {summary?.learners ?? "..."}
            </dd>
          </div>
          <div>
            <dt className="text-ink/70 text-xs">Seeded sessions</dt>
            <dd data-testid="demo-sessions" className="text-ink text-lg font-semibold">
              {summary?.sessions ?? "..."}
            </dd>
          </div>
        </dl>
      </section>

      <section aria-label="Reset the demo" className="mt-6">
        {!confirming ? (
          <button
            type="button"
            onClick={() => setConfirming(true)}
            disabled={busy}
            data-testid="demo-reset-btn"
            className="bg-neem rounded-lg px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"
          >
            Reset demo data
          </button>
        ) : (
          <div role="alertdialog" aria-label="Confirm reset" className="flex flex-col gap-3">
            <p className="text-ink text-sm">
              This removes {summary?.sessions ?? 0} seeded demo sessions and generates a fresh set.
              Uploaded content and real learner work are not touched.
            </p>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => void reset()}
                disabled={busy}
                data-testid="demo-reset-confirm"
                className="bg-kattha rounded-lg px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"
              >
                {busy ? "Resetting..." : "Yes, reset"}
              </button>
              <button
                type="button"
                onClick={() => setConfirming(false)}
                disabled={busy}
                className="border-mist text-ink rounded-lg border px-4 py-2 text-sm font-semibold"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
      </section>

      {message && (
        <p role="status" data-testid="demo-message" className="text-ink mt-4 text-sm">
          {message}
        </p>
      )}
      {error && (
        <p role="alert" className="text-kattha mt-4 text-sm">
          {error}
        </p>
      )}
    </main>
  );
}
